import { Button } from '@/components/ui/button';
import { ArrowLeft } from 'lucide-react';
import { useNavigate, Link } from 'react-router-dom';

const Disclaimer = () => {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-background">
      <header className="fixed top-0 left-0 right-0 z-10 bg-background/80 backdrop-blur-sm border-b border-border">
        <div className="max-w-4xl mx-auto px-6 py-1 flex justify-between items-center">
          <Link to="/" className="flex items-center hover:opacity-90 transition-opacity">
            <img
              src="/lovable-uploads/97d2794e-ae8f-4125-bd01-20fe8dac93f8.png"
              alt="umamic logo"
              className="h-32 w-auto"
              loading="lazy"
            />
            <span className="sr-only">umamic home</span>
          </Link>
          
          <Button
            variant="ghost"
            onClick={() => navigate(-1)}
            className="text-muted-foreground hover:text-foreground"
          >
            <ArrowLeft className="w-4 h-4 mr-2" />
            back
          </Button>
        </div>
      </header>

      <main className="pt-24 pb-32">
        <div className="max-w-4xl mx-auto px-6">
          <h1 className="text-4xl font-bold mb-8">disclaimer</h1>
          
          <div className="space-y-6 text-muted-foreground">
            <div className="bg-destructive/10 border border-destructive/20 rounded-lg p-6">
              <h2 className="text-xl font-semibold text-destructive mb-4">⚠️ important notice</h2>
              <p>umamic provides ai-generated recipe content for informational and entertainment purposes only.</p>
            </div>
            
            <div className="space-y-4">
              <h2 className="text-2xl font-semibold text-foreground">we are not responsible for:</h2>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li>allergic reactions or dietary conflicts</li>
                <li>cooking safety (e.g., undercooked ingredients)</li>
                <li>accuracy of ingredient substitutions or measurements</li>
              </ul>
            </div>

            <div className="bg-muted/50 rounded-lg p-6">
              <p className="font-medium">
                use recipes at your own risk. if you have dietary restrictions or health conditions, 
                consult a medical or culinary professional before trying any recipe generated by umamic.
              </p>
            </div>

            <div className="space-y-4">
              <h2 className="text-2xl font-semibold text-foreground">safety guidelines</h2>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li>always verify ingredient safety and compatibility</li>
                <li>follow proper food handling and cooking temperatures</li>
                <li>be aware of potential allergens in ingredients</li>
                <li>use your best judgment when following ai-generated instructions</li>
              </ul>
            </div>

            <div className="space-y-4">
              <h2 className="text-2xl font-semibold text-foreground">contact</h2>
              <p>for questions about this disclaimer, contact:<br/>
              📧 <a href="mailto:hiumamic@outlook.com" className="underline">hiumamic@outlook.com</a></p>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Disclaimer;