import { Button } from '@/components/ui/button';
import { ArrowLeft } from 'lucide-react';
import { useNavigate } from 'react-router-dom';

const Disclaimer = () => {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-background">
      <header className="fixed top-0 left-0 right-0 z-10 bg-background/80 backdrop-blur-sm border-b border-border">
        <div className="max-w-4xl mx-auto px-6 py-4 flex justify-between items-center">
          <button 
            onClick={() => navigate('/')}
            className="text-2xl font-bold tracking-tight hover:text-muted-foreground transition-colors"
          >
            umamic
          </button>
          
          <Button
            variant="ghost"
            onClick={() => navigate(-1)}
            className="text-muted-foreground hover:text-foreground"
          >
            <ArrowLeft className="w-4 h-4 mr-2" />
            back
          </Button>
        </div>
      </header>

      <main className="pt-24 pb-32">
        <div className="max-w-4xl mx-auto px-6">
          <h1 className="text-4xl font-bold mb-8">Disclaimer</h1>
          
          <div className="space-y-6 text-muted-foreground">
            <div className="bg-destructive/10 border border-destructive/20 rounded-lg p-6">
              <h2 className="text-xl font-semibold text-destructive mb-4">⚠️ Important Notice</h2>
              <p>Umamic provides AI-generated recipe content for informational and entertainment purposes only.</p>
            </div>
            
            <div className="space-y-4">
              <h2 className="text-2xl font-semibold text-foreground">We are not responsible for:</h2>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li>Allergic reactions or dietary conflicts</li>
                <li>Cooking safety (e.g., undercooked ingredients)</li>
                <li>Accuracy of ingredient substitutions or measurements</li>
              </ul>
            </div>

            <div className="bg-muted/50 rounded-lg p-6">
              <p className="font-medium">
                Use recipes at your own risk. If you have dietary restrictions or health conditions, 
                consult a medical or culinary professional before trying any recipe generated by Umamic.
              </p>
            </div>

            <div className="space-y-4">
              <h2 className="text-2xl font-semibold text-foreground">Safety Guidelines</h2>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li>Always verify ingredient safety and compatibility</li>
                <li>Follow proper food handling and cooking temperatures</li>
                <li>Be aware of potential allergens in ingredients</li>
                <li>Use your best judgment when following AI-generated instructions</li>
              </ul>
            </div>

            <div className="space-y-4">
              <h2 className="text-2xl font-semibold text-foreground">Contact</h2>
              <p>For questions about this disclaimer, contact:<br/>
              📧 <a href="mailto:hiumamic@outlook.com" className="underline">hiumamic@outlook.com</a></p>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Disclaimer;