import { Button } from '@/components/ui/button';
import { ArrowLeft } from 'lucide-react';
import { useNavigate } from 'react-router-dom';

const Terms = () => {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-background">
      <header className="fixed top-0 left-0 right-0 z-10 bg-background/80 backdrop-blur-sm border-b border-border">
        <div className="max-w-4xl mx-auto px-6 py-4 flex justify-between items-center">
          <button 
            onClick={() => navigate('/')}
            className="text-2xl font-bold tracking-tight hover:text-muted-foreground transition-colors"
          >
            umamic
          </button>
          
          <Button
            variant="ghost"
            onClick={() => navigate(-1)}
            className="text-muted-foreground hover:text-foreground"
          >
            <ArrowLeft className="w-4 h-4 mr-2" />
            back
          </Button>
        </div>
      </header>

      <main className="pt-24 pb-32">
        <div className="max-w-4xl mx-auto px-6">
          <h1 className="text-4xl font-bold mb-8">Terms of Service</h1>
          
          <div className="space-y-6 text-muted-foreground">
            <p><strong>Effective Date:</strong> August 4, 2025</p>
            
            <p>By using Umamic, you agree to the following Terms of Service. If you do not agree, please do not use our site.</p>
            
            <div className="space-y-4">
              <h2 className="text-2xl font-semibold text-foreground">1. Use of Service</h2>
              <p>Umamic offers AI-generated recipes based on your input. You may use the site for personal, non-commercial use only.</p>
            </div>

            <div className="space-y-4">
              <h2 className="text-2xl font-semibold text-foreground">2. AI Content</h2>
              <p>All recipes are generated by AI. While we aim for accuracy and creativity, we make no guarantees regarding safety, nutritional value, or outcomes.</p>
            </div>

            <div className="space-y-4">
              <h2 className="text-2xl font-semibold text-foreground">3. User Conduct</h2>
              <p>You agree not to:</p>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li>Use Umamic for illegal or harmful purposes</li>
                <li>Scrape or misuse data</li>
                <li>Interfere with the service's operation</li>
              </ul>
            </div>

            <div className="space-y-4">
              <h2 className="text-2xl font-semibold text-foreground">4. Intellectual Property</h2>
              <p>All content, branding, and design elements are owned by Umamic or its licensors. You may not copy, distribute, or reproduce any part without permission.</p>
            </div>

            <div className="space-y-4">
              <h2 className="text-2xl font-semibold text-foreground">5. Termination</h2>
              <p>We reserve the right to suspend or terminate access to the site at any time, without notice, for any reason.</p>
            </div>

            <div className="space-y-4">
              <h2 className="text-2xl font-semibold text-foreground">6. Disclaimers</h2>
              <p>Umamic is provided "as is." We disclaim all warranties and are not liable for damages, including from incorrect or unsafe recipe results.</p>
            </div>

            <div className="space-y-4">
              <h2 className="text-2xl font-semibold text-foreground">7. Governing Law</h2>
              <p>These Terms are governed by the laws of [Your State/Country]. Disputes will be handled in local courts.</p>
            </div>

            <div className="space-y-4">
              <h2 className="text-2xl font-semibold text-foreground">8. Contact</h2>
              <p>For any legal questions, email: <a href="mailto:hiumamic@outlook.com" className="underline">hiumamic@outlook.com</a></p>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Terms;