import { useState } from 'react';
import { Input } from '@/components/ui/input';
import { Search } from 'lucide-react';

interface Ingredient {
  name: string;
  category: string;
}

const ingredients: Ingredient[] = [
  // proteins
  { name: 'chicken breast', category: 'proteins' },
  { name: 'chicken thigh', category: 'proteins' },
  { name: 'chicken wings', category: 'proteins' },
  { name: 'ground chicken', category: 'proteins' },
  { name: 'turkey', category: 'proteins' },
  { name: 'duck', category: 'proteins' },
  { name: 'pork chops', category: 'proteins' },
  { name: 'pork belly', category: 'proteins' },
  { name: 'pork shoulder', category: 'proteins' },
  { name: 'ground pork', category: 'proteins' },
  { name: 'beef steak', category: 'proteins' },
  { name: 'ground beef', category: 'proteins' },
  { name: 'beef brisket', category: 'proteins' },
  { name: 'short ribs', category: 'proteins' },
  { name: 'lamb chops', category: 'proteins' },
  { name: 'ground lamb', category: 'proteins' },
  { name: 'lamb leg', category: 'proteins' },
  { name: 'goat', category: 'proteins' },
  { name: 'veal', category: 'proteins' },
  { name: 'salmon', category: 'proteins' },
  { name: 'cod', category: 'proteins' },
  { name: 'tuna', category: 'proteins' },
  { name: 'halibut', category: 'proteins' },
  { name: 'sardine', category: 'proteins' },
  { name: 'shrimp', category: 'proteins' },
  { name: 'crab', category: 'proteins' },
  { name: 'lobster', category: 'proteins' },
  { name: 'mussels', category: 'proteins' },
  { name: 'clams', category: 'proteins' },
  { name: 'scallops', category: 'proteins' },
  { name: 'squid', category: 'proteins' },
  { name: 'octopus', category: 'proteins' },
  { name: 'tofu', category: 'proteins' },
  { name: 'tempeh', category: 'proteins' },
  { name: 'seitan', category: 'proteins' },
  { name: 'eggs', category: 'proteins' },
  { name: 'paneer', category: 'proteins' },
  { name: 'halloumi', category: 'proteins' },
  { name: 'plant-based meat', category: 'proteins' },

  // vegetables
  { name: 'carrot', category: 'vegetables' },
  { name: 'potato', category: 'vegetables' },
  { name: 'sweet potato', category: 'vegetables' },
  { name: 'onion', category: 'vegetables' },
  { name: 'red onion', category: 'vegetables' },
  { name: 'white onion', category: 'vegetables' },
  { name: 'yellow onion', category: 'vegetables' },
  { name: 'shallot', category: 'vegetables' },
  { name: 'garlic', category: 'vegetables' },
  { name: 'bell pepper', category: 'vegetables' },
  { name: 'red bell pepper', category: 'vegetables' },
  { name: 'green bell pepper', category: 'vegetables' },
  { name: 'yellow bell pepper', category: 'vegetables' },
  { name: 'jalapeño', category: 'vegetables' },
  { name: 'serrano pepper', category: 'vegetables' },
  { name: 'habanero', category: 'vegetables' },
  { name: 'ghost pepper', category: 'vegetables' },
  { name: 'poblano pepper', category: 'vegetables' },
  { name: 'broccoli', category: 'vegetables' },
  { name: 'cauliflower', category: 'vegetables' },
  { name: 'brussels sprouts', category: 'vegetables' },
  { name: 'spinach', category: 'vegetables' },
  { name: 'kale', category: 'vegetables' },
  { name: 'swiss chard', category: 'vegetables' },
  { name: 'arugula', category: 'vegetables' },
  { name: 'lettuce', category: 'vegetables' },
  { name: 'romaine lettuce', category: 'vegetables' },
  { name: 'iceberg lettuce', category: 'vegetables' },
  { name: 'butter lettuce', category: 'vegetables' },
  { name: 'cabbage', category: 'vegetables' },
  { name: 'red cabbage', category: 'vegetables' },
  { name: 'napa cabbage', category: 'vegetables' },
  { name: 'bok choy', category: 'vegetables' },
  { name: 'collard greens', category: 'vegetables' },
  { name: 'zucchini', category: 'vegetables' },
  { name: 'yellow squash', category: 'vegetables' },
  { name: 'butternut squash', category: 'vegetables' },
  { name: 'acorn squash', category: 'vegetables' },
  { name: 'kabocha squash', category: 'vegetables' },
  { name: 'delicata squash', category: 'vegetables' },
  { name: 'pumpkin', category: 'vegetables' },
  { name: 'eggplant', category: 'vegetables' },
  { name: 'japanese eggplant', category: 'vegetables' },
  { name: 'tomato', category: 'vegetables' },
  { name: 'cherry tomato', category: 'vegetables' },
  { name: 'grape tomato', category: 'vegetables' },
  { name: 'roma tomato', category: 'vegetables' },
  { name: 'beefsteak tomato', category: 'vegetables' },
  { name: 'heirloom tomato', category: 'vegetables' },
  { name: 'cucumber', category: 'vegetables' },
  { name: 'english cucumber', category: 'vegetables' },
  { name: 'persian cucumber', category: 'vegetables' },
  { name: 'celery', category: 'vegetables' },
  { name: 'leek', category: 'vegetables' },
  { name: 'fennel', category: 'vegetables' },
  { name: 'radish', category: 'vegetables' },
  { name: 'daikon radish', category: 'vegetables' },
  { name: 'watermelon radish', category: 'vegetables' },
  { name: 'beet', category: 'vegetables' },
  { name: 'golden beet', category: 'vegetables' },
  { name: 'chioggia beet', category: 'vegetables' },
  { name: 'green beans', category: 'vegetables' },
  { name: 'snap peas', category: 'vegetables' },
  { name: 'snow peas', category: 'vegetables' },
  { name: 'sugar snap peas', category: 'vegetables' },
  { name: 'peas', category: 'vegetables' },
  { name: 'artichoke', category: 'vegetables' },
  { name: 'baby artichoke', category: 'vegetables' },
  { name: 'asparagus', category: 'vegetables' },
  { name: 'okra', category: 'vegetables' },
  { name: 'chayote', category: 'vegetables' },
  { name: 'corn', category: 'vegetables' },
  { name: 'baby corn', category: 'vegetables' },
  { name: 'turnip', category: 'vegetables' },
  { name: 'rutabaga', category: 'vegetables' },
  { name: 'parsnip', category: 'vegetables' },
  { name: 'jicama', category: 'vegetables' },
  { name: 'water chestnuts', category: 'vegetables' },
  { name: 'bamboo shoots', category: 'vegetables' },
  { name: 'hearts of palm', category: 'vegetables' },
  { name: 'button mushroom', category: 'vegetables' },
  { name: 'cremini mushroom', category: 'vegetables' },
  { name: 'portobello mushroom', category: 'vegetables' },
  { name: 'shiitake mushroom', category: 'vegetables' },
  { name: 'oyster mushroom', category: 'vegetables' },
  { name: 'enoki mushroom', category: 'vegetables' },
  { name: 'maitake mushroom', category: 'vegetables' },
  { name: 'morel mushroom', category: 'vegetables' },
  { name: 'chanterelle mushroom', category: 'vegetables' },
  { name: 'porcini mushroom', category: 'vegetables' },
  { name: 'king oyster mushroom', category: 'vegetables' },

  // fruits
  { name: 'apple', category: 'fruits' },
  { name: 'green apple', category: 'fruits' },
  { name: 'red apple', category: 'fruits' },
  { name: 'honeycrisp apple', category: 'fruits' },
  { name: 'granny smith apple', category: 'fruits' },
  { name: 'gala apple', category: 'fruits' },
  { name: 'fuji apple', category: 'fruits' },
  { name: 'banana', category: 'fruits' },
  { name: 'plantain', category: 'fruits' },
  { name: 'orange', category: 'fruits' },
  { name: 'blood orange', category: 'fruits' },
  { name: 'naval orange', category: 'fruits' },
  { name: 'mandarin', category: 'fruits' },
  { name: 'tangerine', category: 'fruits' },
  { name: 'clementine', category: 'fruits' },
  { name: 'lemon', category: 'fruits' },
  { name: 'meyer lemon', category: 'fruits' },
  { name: 'lime', category: 'fruits' },
  { name: 'key lime', category: 'fruits' },
  { name: 'persian lime', category: 'fruits' },
  { name: 'grapefruit', category: 'fruits' },
  { name: 'pink grapefruit', category: 'fruits' },
  { name: 'white grapefruit', category: 'fruits' },
  { name: 'mango', category: 'fruits' },
  { name: 'tommy mango', category: 'fruits' },
  { name: 'ataulfo mango', category: 'fruits' },
  { name: 'pineapple', category: 'fruits' },
  { name: 'strawberry', category: 'fruits' },
  { name: 'raspberry', category: 'fruits' },
  { name: 'blackberry', category: 'fruits' },
  { name: 'blueberry', category: 'fruits' },
  { name: 'huckleberry', category: 'fruits' },
  { name: 'cranberry', category: 'fruits' },
  { name: 'cherry', category: 'fruits' },
  { name: 'sweet cherry', category: 'fruits' },
  { name: 'tart cherry', category: 'fruits' },
  { name: 'grape', category: 'fruits' },
  { name: 'red grape', category: 'fruits' },
  { name: 'green grape', category: 'fruits' },
  { name: 'concord grape', category: 'fruits' },
  { name: 'kiwi', category: 'fruits' },
  { name: 'golden kiwi', category: 'fruits' },
  { name: 'watermelon', category: 'fruits' },
  { name: 'seedless watermelon', category: 'fruits' },
  { name: 'yellow watermelon', category: 'fruits' },
  { name: 'cantaloupe', category: 'fruits' },
  { name: 'honeydew', category: 'fruits' },
  { name: 'crenshaw melon', category: 'fruits' },
  { name: 'casaba melon', category: 'fruits' },
  { name: 'pear', category: 'fruits' },
  { name: 'bartlett pear', category: 'fruits' },
  { name: 'anjou pear', category: 'fruits' },
  { name: 'bosc pear', category: 'fruits' },
  { name: 'asian pear', category: 'fruits' },
  { name: 'peach', category: 'fruits' },
  { name: 'white peach', category: 'fruits' },
  { name: 'yellow peach', category: 'fruits' },
  { name: 'donut peach', category: 'fruits' },
  { name: 'nectarine', category: 'fruits' },
  { name: 'white nectarine', category: 'fruits' },
  { name: 'plum', category: 'fruits' },
  { name: 'red plum', category: 'fruits' },
  { name: 'black plum', category: 'fruits' },
  { name: 'italian plum', category: 'fruits' },
  { name: 'apricot', category: 'fruits' },
  { name: 'fig', category: 'fruits' },
  { name: 'fresh fig', category: 'fruits' },
  { name: 'black mission fig', category: 'fruits' },
  { name: 'brown turkey fig', category: 'fruits' },
  { name: 'date', category: 'fruits' },
  { name: 'medjool date', category: 'fruits' },
  { name: 'deglet noor date', category: 'fruits' },
  { name: 'papaya', category: 'fruits' },
  { name: 'mexican papaya', category: 'fruits' },
  { name: 'guava', category: 'fruits' },
  { name: 'lychee', category: 'fruits' },
  { name: 'rambutan', category: 'fruits' },
  { name: 'longan', category: 'fruits' },
  { name: 'dragon fruit', category: 'fruits' },
  { name: 'passion fruit', category: 'fruits' },
  { name: 'star fruit', category: 'fruits' },
  { name: 'persimmon', category: 'fruits' },
  { name: 'fuyu persimmon', category: 'fruits' },
  { name: 'hachiya persimmon', category: 'fruits' },
  { name: 'pomegranate', category: 'fruits' },
  { name: 'coconut', category: 'fruits' },
  { name: 'young coconut', category: 'fruits' },
  { name: 'avocado', category: 'fruits' },
  { name: 'hass avocado', category: 'fruits' },
  { name: 'fuerte avocado', category: 'fruits' },

  // grains & flours
  { name: 'white rice', category: 'grains' },
  { name: 'brown rice', category: 'grains' },
  { name: 'jasmine rice', category: 'grains' },
  { name: 'basmati rice', category: 'grains' },
  { name: 'wild rice', category: 'grains' },
  { name: 'arborio rice', category: 'grains' },
  { name: 'bomba rice', category: 'grains' },
  { name: 'black rice', category: 'grains' },
  { name: 'red rice', category: 'grains' },
  { name: 'sticky rice', category: 'grains' },
  { name: 'quinoa', category: 'grains' },
  { name: 'red quinoa', category: 'grains' },
  { name: 'black quinoa', category: 'grains' },
  { name: 'tri-color quinoa', category: 'grains' },
  { name: 'bulgur', category: 'grains' },
  { name: 'fine bulgur', category: 'grains' },
  { name: 'coarse bulgur', category: 'grains' },
  { name: 'couscous', category: 'grains' },
  { name: 'israeli couscous', category: 'grains' },
  { name: 'barley', category: 'grains' },
  { name: 'pearl barley', category: 'grains' },
  { name: 'hulled barley', category: 'grains' },
  { name: 'farro', category: 'grains' },
  { name: 'emmer farro', category: 'grains' },
  { name: 'spelt', category: 'grains' },
  { name: 'kamut', category: 'grains' },
  { name: 'oats', category: 'grains' },
  { name: 'rolled oats', category: 'grains' },
  { name: 'steel cut oats', category: 'grains' },
  { name: 'instant oats', category: 'grains' },
  { name: 'oat groats', category: 'grains' },
  { name: 'cornmeal', category: 'grains' },
  { name: 'fine cornmeal', category: 'grains' },
  { name: 'coarse cornmeal', category: 'grains' },
  { name: 'polenta', category: 'grains' },
  { name: 'wheat berries', category: 'grains' },
  { name: 'hard red wheat berries', category: 'grains' },
  { name: 'soft white wheat berries', category: 'grains' },
  { name: 'millet', category: 'grains' },
  { name: 'amaranth', category: 'grains' },
  { name: 'teff', category: 'grains' },
  { name: 'sorghum', category: 'grains' },
  { name: 'rye', category: 'grains' },
  { name: 'rye berries', category: 'grains' },
  { name: 'buckwheat', category: 'grains' },
  { name: 'buckwheat groats', category: 'grains' },
  { name: 'semolina', category: 'grains' },
  { name: 'durum semolina', category: 'grains' },
  { name: 'all-purpose flour', category: 'grains' },
  { name: 'bread flour', category: 'grains' },
  { name: 'cake flour', category: 'grains' },
  { name: 'pastry flour', category: 'grains' },
  { name: 'whole wheat flour', category: 'grains' },
  { name: 'white whole wheat flour', category: 'grains' },
  { name: 'spelt flour', category: 'grains' },
  { name: 'rye flour', category: 'grains' },
  { name: 'buckwheat flour', category: 'grains' },
  { name: 'almond flour', category: 'grains' },
  { name: 'almond meal', category: 'grains' },
  { name: 'chickpea flour', category: 'grains' },
  { name: 'rice flour', category: 'grains' },
  { name: 'brown rice flour', category: 'grains' },
  { name: 'glutinous rice flour', category: 'grains' },
  { name: 'corn flour', category: 'grains' },
  { name: 'masa harina', category: 'grains' },
  { name: 'tapioca flour', category: 'grains' },
  { name: 'tapioca starch', category: 'grains' },
  { name: 'potato starch', category: 'grains' },
  { name: 'potato flour', category: 'grains' },
  { name: 'cassava flour', category: 'grains' },
  { name: 'coconut flour', category: 'grains' },

  // dairy & alternatives
  { name: 'cow milk', category: 'dairy' },
  { name: 'whole milk', category: 'dairy' },
  { name: '2% milk', category: 'dairy' },
  { name: '1% milk', category: 'dairy' },
  { name: 'skim milk', category: 'dairy' },
  { name: 'goat milk', category: 'dairy' },
  { name: 'sheep milk', category: 'dairy' },
  { name: 'cream', category: 'dairy' },
  { name: 'heavy cream', category: 'dairy' },
  { name: 'heavy whipping cream', category: 'dairy' },
  { name: 'light cream', category: 'dairy' },
  { name: 'half-and-half', category: 'dairy' },
  { name: 'whipping cream', category: 'dairy' },
  { name: 'clotted cream', category: 'dairy' },
  { name: 'crème fraîche', category: 'dairy' },
  { name: 'butter', category: 'dairy' },
  { name: 'unsalted butter', category: 'dairy' },
  { name: 'salted butter', category: 'dairy' },
  { name: 'european butter', category: 'dairy' },
  { name: 'clarified butter', category: 'dairy' },
  { name: 'ghee', category: 'dairy' },
  { name: 'cheddar cheese', category: 'dairy' },
  { name: 'sharp cheddar', category: 'dairy' },
  { name: 'mild cheddar', category: 'dairy' },
  { name: 'mozzarella cheese', category: 'dairy' },
  { name: 'fresh mozzarella', category: 'dairy' },
  { name: 'buffalo mozzarella', category: 'dairy' },
  { name: 'feta cheese', category: 'dairy' },
  { name: 'greek feta', category: 'dairy' },
  { name: 'french feta', category: 'dairy' },
  { name: 'parmesan cheese', category: 'dairy' },
  { name: 'parmigiano-reggiano', category: 'dairy' },
  { name: 'pecorino romano', category: 'dairy' },
  { name: 'gruyere cheese', category: 'dairy' },
  { name: 'swiss cheese', category: 'dairy' },
  { name: 'emmental cheese', category: 'dairy' },
  { name: 'gouda cheese', category: 'dairy' },
  { name: 'aged gouda', category: 'dairy' },
  { name: 'smoked gouda', category: 'dairy' },
  { name: 'brie cheese', category: 'dairy' },
  { name: 'camembert cheese', category: 'dairy' },
  { name: 'blue cheese', category: 'dairy' },
  { name: 'roquefort cheese', category: 'dairy' },
  { name: 'gorgonzola cheese', category: 'dairy' },
  { name: 'stilton cheese', category: 'dairy' },
  { name: 'goat cheese', category: 'dairy' },
  { name: 'cream cheese', category: 'dairy' },
  { name: 'ricotta cheese', category: 'dairy' },
  { name: 'cottage cheese', category: 'dairy' },
  { name: 'mascarpone cheese', category: 'dairy' },
  { name: 'yogurt', category: 'dairy' },
  { name: 'greek yogurt', category: 'dairy' },
  { name: 'plain yogurt', category: 'dairy' },
  { name: 'vanilla yogurt', category: 'dairy' },
  { name: 'sour cream', category: 'dairy' },
  { name: 'buttermilk', category: 'dairy' },
  { name: 'kefir', category: 'dairy' },
  { name: 'condensed milk', category: 'dairy' },
  { name: 'sweetened condensed milk', category: 'dairy' },
  { name: 'evaporated milk', category: 'dairy' },
  { name: 'powdered milk', category: 'dairy' },
  { name: 'oat milk', category: 'dairy' },
  { name: 'almond milk', category: 'dairy' },
  { name: 'unsweetened almond milk', category: 'dairy' },
  { name: 'vanilla almond milk', category: 'dairy' },
  { name: 'soy milk', category: 'dairy' },
  { name: 'unsweetened soy milk', category: 'dairy' },
  { name: 'vanilla soy milk', category: 'dairy' },
  { name: 'coconut milk', category: 'dairy' },
  { name: 'light coconut milk', category: 'dairy' },
  { name: 'full-fat coconut milk', category: 'dairy' },
  { name: 'rice milk', category: 'dairy' },
  { name: 'cashew milk', category: 'dairy' },
  { name: 'pea milk', category: 'dairy' },
  { name: 'hemp milk', category: 'dairy' },
  { name: 'macadamia milk', category: 'dairy' },
  { name: 'vegan butter', category: 'dairy' },
  { name: 'vegan cheese', category: 'dairy' },
  { name: 'nutritional yeast', category: 'dairy' },

  // spices & herbs
  { name: 'salt', category: 'spices' },
  { name: 'sea salt', category: 'spices' },
  { name: 'kosher salt', category: 'spices' },
  { name: 'himalayan salt', category: 'spices' },
  { name: 'black pepper', category: 'spices' },
  { name: 'white pepper', category: 'spices' },
  { name: 'sichuan pepper', category: 'spices' },
  { name: 'paprika', category: 'spices' },
  { name: 'smoked paprika', category: 'spices' },
  { name: 'chili powder', category: 'spices' },
  { name: 'cayenne', category: 'spices' },
  { name: 'chipotle powder', category: 'spices' },
  { name: 'red pepper flakes', category: 'spices' },
  { name: 'turmeric', category: 'spices' },
  { name: 'cumin', category: 'spices' },
  { name: 'ground cumin', category: 'spices' },
  { name: 'coriander', category: 'spices' },
  { name: 'ground coriander', category: 'spices' },
  { name: 'mustard seeds', category: 'spices' },
  { name: 'dry mustard', category: 'spices' },
  { name: 'fenugreek', category: 'spices' },
  { name: 'garam masala', category: 'spices' },
  { name: 'curry powder', category: 'spices' },
  { name: 'madras curry', category: 'spices' },
  { name: 'chinese five spice', category: 'spices' },
  { name: 'italian seasoning', category: 'spices' },
  { name: 'herbes de provence', category: 'spices' },
  { name: 'old bay seasoning', category: 'spices' },
  { name: 'taco seasoning', category: 'spices' },
  { name: 'ranch seasoning', category: 'spices' },
  { name: 'onion powder', category: 'spices' },
  { name: 'garlic powder', category: 'spices' },
  { name: 'celery seed', category: 'spices' },
  { name: 'fennel seeds', category: 'spices' },
  { name: 'caraway seeds', category: 'spices' },
  { name: 'cinnamon', category: 'spices' },
  { name: 'ground cinnamon', category: 'spices' },
  { name: 'cinnamon stick', category: 'spices' },
  { name: 'nutmeg', category: 'spices' },
  { name: 'ground nutmeg', category: 'spices' },
  { name: 'clove', category: 'spices' },
  { name: 'ground cloves', category: 'spices' },
  { name: 'cardamom', category: 'spices' },
  { name: 'ground cardamom', category: 'spices' },
  { name: 'allspice', category: 'spices' },
  { name: 'ground allspice', category: 'spices' },
  { name: 'bay leaf', category: 'spices' },
  { name: 'star anise', category: 'spices' },
  { name: 'vanilla bean', category: 'spices' },
  { name: 'vanilla powder', category: 'spices' },
  { name: 'dill', category: 'spices' },
  { name: 'dried dill', category: 'spices' },
  { name: 'parsley', category: 'spices' },
  { name: 'dried parsley', category: 'spices' },
  { name: 'basil', category: 'spices' },
  { name: 'dried basil', category: 'spices' },
  { name: 'oregano', category: 'spices' },
  { name: 'dried oregano', category: 'spices' },
  { name: 'thyme', category: 'spices' },
  { name: 'dried thyme', category: 'spices' },
  { name: 'rosemary', category: 'spices' },
  { name: 'dried rosemary', category: 'spices' },
  { name: 'sage', category: 'spices' },
  { name: 'dried sage', category: 'spices' },
  { name: 'mint', category: 'spices' },
  { name: 'dried mint', category: 'spices' },
  { name: 'chives', category: 'spices' },
  { name: 'dried chives', category: 'spices' },
  { name: 'tarragon', category: 'spices' },
  { name: 'dried tarragon', category: 'spices' },
  { name: 'za\'atar', category: 'spices' },
  { name: 'sumac', category: 'spices' },
  { name: 'berbere', category: 'spices' },
  { name: 'ras el hanout', category: 'spices' },
  { name: 'dukkah', category: 'spices' },
  { name: 'fresh ginger', category: 'spices' },
  { name: 'ground ginger', category: 'spices' },
  { name: 'galangal', category: 'spices' },
  { name: 'lemongrass', category: 'spices' },
  { name: 'kaffir lime leaves', category: 'spices' },

  // condiments & oils
  { name: 'olive oil', category: 'condiments' },
  { name: 'extra virgin olive oil', category: 'condiments' },
  { name: 'light olive oil', category: 'condiments' },
  { name: 'vegetable oil', category: 'condiments' },
  { name: 'canola oil', category: 'condiments' },
  { name: 'sunflower oil', category: 'condiments' },
  { name: 'safflower oil', category: 'condiments' },
  { name: 'grapeseed oil', category: 'condiments' },
  { name: 'avocado oil', category: 'condiments' },
  { name: 'coconut oil', category: 'condiments' },
  { name: 'sesame oil', category: 'condiments' },
  { name: 'toasted sesame oil', category: 'condiments' },
  { name: 'walnut oil', category: 'condiments' },
  { name: 'hazelnut oil', category: 'condiments' },
  { name: 'truffle oil', category: 'condiments' },
  { name: 'chili oil', category: 'condiments' },
  { name: 'soy sauce', category: 'condiments' },
  { name: 'low sodium soy sauce', category: 'condiments' },
  { name: 'dark soy sauce', category: 'condiments' },
  { name: 'light soy sauce', category: 'condiments' },
  { name: 'tamari', category: 'condiments' },
  { name: 'coconut aminos', category: 'condiments' },
  { name: 'fish sauce', category: 'condiments' },
  { name: 'oyster sauce', category: 'condiments' },
  { name: 'hoisin sauce', category: 'condiments' },
  { name: 'teriyaki sauce', category: 'condiments' },
  { name: 'ponzu sauce', category: 'condiments' },
  { name: 'mirin', category: 'condiments' },
  { name: 'sake', category: 'condiments' },
  { name: 'worcestershire sauce', category: 'condiments' },
  { name: 'balsamic vinegar', category: 'condiments' },
  { name: 'aged balsamic vinegar', category: 'condiments' },
  { name: 'white balsamic vinegar', category: 'condiments' },
  { name: 'red wine vinegar', category: 'condiments' },
  { name: 'white wine vinegar', category: 'condiments' },
  { name: 'champagne vinegar', category: 'condiments' },
  { name: 'sherry vinegar', category: 'condiments' },
  { name: 'white vinegar', category: 'condiments' },
  { name: 'apple cider vinegar', category: 'condiments' },
  { name: 'rice vinegar', category: 'condiments' },
  { name: 'seasoned rice vinegar', category: 'condiments' },
  { name: 'black vinegar', category: 'condiments' },
  { name: 'malt vinegar', category: 'condiments' },
  { name: 'ketchup', category: 'condiments' },
  { name: 'organic ketchup', category: 'condiments' },
  { name: 'mustard', category: 'condiments' },
  { name: 'dijon mustard', category: 'condiments' },
  { name: 'whole grain mustard', category: 'condiments' },
  { name: 'yellow mustard', category: 'condiments' },
  { name: 'spicy brown mustard', category: 'condiments' },
  { name: 'honey mustard', category: 'condiments' },
  { name: 'mayonnaise', category: 'condiments' },
  { name: 'vegan mayonnaise', category: 'condiments' },
  { name: 'aioli', category: 'condiments' },
  { name: 'hot sauce', category: 'condiments' },
  { name: 'sriracha', category: 'condiments' },
  { name: 'tabasco', category: 'condiments' },
  { name: 'cholula', category: 'condiments' },
  { name: 'sambal oelek', category: 'condiments' },
  { name: 'gochujang', category: 'condiments' },
  { name: 'harissa', category: 'condiments' },
  { name: 'bbq sauce', category: 'condiments' },
  { name: 'kansas city bbq sauce', category: 'condiments' },
  { name: 'carolina bbq sauce', category: 'condiments' },
  { name: 'tahini', category: 'condiments' },
  { name: 'pesto', category: 'condiments' },
  { name: 'basil pesto', category: 'condiments' },
  { name: 'sun-dried tomato pesto', category: 'condiments' },
  { name: 'miso', category: 'condiments' },
  { name: 'white miso', category: 'condiments' },
  { name: 'red miso', category: 'condiments' },
  { name: 'peanut butter', category: 'condiments' },
  { name: 'natural peanut butter', category: 'condiments' },
  { name: 'crunchy peanut butter', category: 'condiments' },
  { name: 'almond butter', category: 'condiments' },
  { name: 'cashew butter', category: 'condiments' },
  { name: 'sunflower seed butter', category: 'condiments' },
  { name: 'jam', category: 'condiments' },
  { name: 'strawberry jam', category: 'condiments' },
  { name: 'grape jelly', category: 'condiments' },
  { name: 'apricot jam', category: 'condiments' },
  { name: 'orange marmalade', category: 'condiments' },
  { name: 'honey', category: 'condiments' },
  { name: 'raw honey', category: 'condiments' },
  { name: 'manuka honey', category: 'condiments' },
  { name: 'clover honey', category: 'condiments' },
  { name: 'wildflower honey', category: 'condiments' },
  { name: 'maple syrup', category: 'condiments' },
  { name: 'pure maple syrup', category: 'condiments' },
  { name: 'grade a maple syrup', category: 'condiments' },
  { name: 'molasses', category: 'condiments' },
  { name: 'blackstrap molasses', category: 'condiments' },
  { name: 'corn syrup', category: 'condiments' },
  { name: 'golden syrup', category: 'condiments' },

  // breads
  { name: 'white bread', category: 'breads' },
  { name: 'whole wheat bread', category: 'breads' },
  { name: 'multigrain bread', category: 'breads' },
  { name: 'rye bread', category: 'breads' },
  { name: 'pumpernickel bread', category: 'breads' },
  { name: 'sourdough', category: 'breads' },
  { name: 'sourdough starter', category: 'breads' },
  { name: 'french bread', category: 'breads' },
  { name: 'baguette', category: 'breads' },
  { name: 'italian bread', category: 'breads' },
  { name: 'ciabatta', category: 'breads' },
  { name: 'focaccia', category: 'breads' },
  { name: 'pita', category: 'breads' },
  { name: 'whole wheat pita', category: 'breads' },
  { name: 'naan', category: 'breads' },
  { name: 'garlic naan', category: 'breads' },
  { name: 'tortilla', category: 'breads' },
  { name: 'flour tortilla', category: 'breads' },
  { name: 'corn tortilla', category: 'breads' },
  { name: 'whole wheat tortilla', category: 'breads' },
  { name: 'roti', category: 'breads' },
  { name: 'chapati', category: 'breads' },
  { name: 'english muffin', category: 'breads' },
  { name: 'whole wheat english muffin', category: 'breads' },
  { name: 'croissant', category: 'breads' },
  { name: 'pain au chocolat', category: 'breads' },
  { name: 'brioche', category: 'breads' },
  { name: 'challah', category: 'breads' },
  { name: 'bagel', category: 'breads' },
  { name: 'everything bagel', category: 'breads' },
  { name: 'sesame bagel', category: 'breads' },
  { name: 'poppy seed bagel', category: 'breads' },
  { name: 'pizza dough', category: 'breads' },
  { name: 'thin crust pizza dough', category: 'breads' },
  { name: 'puff pastry', category: 'breads' },
  { name: 'phyllo dough', category: 'breads' },
  { name: 'pie crust', category: 'breads' },
  { name: 'graham cracker crust', category: 'breads' },

  // pantry
  { name: 'white sugar', category: 'pantry' },
  { name: 'brown sugar', category: 'pantry' },
  { name: 'powdered sugar', category: 'pantry' },
  { name: 'coconut sugar', category: 'pantry' },
  { name: 'agave nectar', category: 'pantry' },
  { name: 'stevia', category: 'pantry' },
  { name: 'baking powder', category: 'pantry' },
  { name: 'baking soda', category: 'pantry' },
  { name: 'cream of tartar', category: 'pantry' },
  { name: 'cornstarch', category: 'pantry' },
  { name: 'arrowroot powder', category: 'pantry' },
  { name: 'yeast', category: 'pantry' },
  { name: 'vanilla extract', category: 'pantry' },
  { name: 'almond extract', category: 'pantry' },
  { name: 'coconut extract', category: 'pantry' },
  { name: 'peppermint extract', category: 'pantry' },
  { name: 'cocoa powder', category: 'pantry' },
  { name: 'chocolate chips', category: 'pantry' },
  { name: 'dark chocolate', category: 'pantry' },
  { name: 'milk chocolate', category: 'pantry' },
  { name: 'white chocolate', category: 'pantry' },
  { name: 'food coloring', category: 'pantry' },
  { name: 'sprinkles', category: 'pantry' },
  { name: 'canned tomatoes', category: 'pantry' },
  { name: 'tomato paste', category: 'pantry' },
  { name: 'tomato sauce', category: 'pantry' },
  { name: 'black beans', category: 'pantry' },
  { name: 'kidney beans', category: 'pantry' },
  { name: 'chickpeas', category: 'pantry' },
  { name: 'white beans', category: 'pantry' },
  { name: 'pinto beans', category: 'pantry' },
  { name: 'red lentils', category: 'pantry' },
  { name: 'green lentils', category: 'pantry' },
  { name: 'black lentils', category: 'pantry' },
  { name: 'split peas', category: 'pantry' },
  { name: 'chicken broth', category: 'pantry' },
  { name: 'beef broth', category: 'pantry' },
  { name: 'vegetable broth', category: 'pantry' },
  { name: 'bone broth', category: 'pantry' },
  { name: 'coconut milk canned', category: 'pantry' },
  { name: 'spaghetti', category: 'pantry' },
  { name: 'penne', category: 'pantry' },
  { name: 'fusilli', category: 'pantry' },
  { name: 'linguine', category: 'pantry' },
  { name: 'fettuccine', category: 'pantry' },
  { name: 'angel hair pasta', category: 'pantry' },
  { name: 'farfalle', category: 'pantry' },
  { name: 'rigatoni', category: 'pantry' },
  { name: 'lasagna sheets', category: 'pantry' },
  { name: 'macaroni', category: 'pantry' },
  { name: 'ramen', category: 'pantry' },
  { name: 'instant noodles', category: 'pantry' },
  { name: 'rice noodles', category: 'pantry' },
  { name: 'glass noodles', category: 'pantry' },
  { name: 'udon noodles', category: 'pantry' },
  { name: 'soba noodles', category: 'pantry' },
  { name: 'almonds', category: 'pantry' },
  { name: 'walnuts', category: 'pantry' },
  { name: 'pistachios', category: 'pantry' },
  { name: 'cashews', category: 'pantry' },
  { name: 'pecans', category: 'pantry' },
  { name: 'hazelnuts', category: 'pantry' },
  { name: 'brazil nuts', category: 'pantry' },
  { name: 'macadamia nuts', category: 'pantry' },
  { name: 'pine nuts', category: 'pantry' },
  { name: 'peanuts', category: 'pantry' },
  { name: 'chia seeds', category: 'pantry' },
  { name: 'flax seeds', category: 'pantry' },
  { name: 'sesame seeds', category: 'pantry' },
  { name: 'sunflower seeds', category: 'pantry' },
  { name: 'pumpkin seeds', category: 'pantry' },
  { name: 'hemp seeds', category: 'pantry' },
  { name: 'poppy seeds', category: 'pantry' },
  { name: 'raisins', category: 'pantry' },
  { name: 'dried cranberries', category: 'pantry' },
  { name: 'dried apricots', category: 'pantry' },
  { name: 'dried dates', category: 'pantry' },
  { name: 'dried figs', category: 'pantry' },
  { name: 'coconut flakes', category: 'pantry' },
  { name: 'coconut flour', category: 'pantry' },
  { name: 'canned fruit', category: 'pantry' },
  { name: 'canned peaches', category: 'pantry' },
  { name: 'canned pears', category: 'pantry' },
  { name: 'applesauce', category: 'pantry' },
  { name: 'fruit preserves', category: 'pantry' },

  // drinks
  { name: 'sparkling water', category: 'drinks' },
  { name: 'soda', category: 'drinks' },
  { name: 'coffee', category: 'drinks' },
  { name: 'espresso', category: 'drinks' },
  { name: 'black tea', category: 'drinks' },
  { name: 'green tea', category: 'drinks' },
  { name: 'white tea', category: 'drinks' },
  { name: 'oolong tea', category: 'drinks' },
  { name: 'herbal tea', category: 'drinks' },
  { name: 'chamomile tea', category: 'drinks' },
  { name: 'peppermint tea', category: 'drinks' },
  { name: 'coconut water', category: 'drinks' },
  { name: 'orange juice', category: 'drinks' },
  { name: 'apple juice', category: 'drinks' },
  { name: 'cranberry juice', category: 'drinks' },
  { name: 'pomegranate juice', category: 'drinks' },
  { name: 'grape juice', category: 'drinks' },
  { name: 'tomato juice', category: 'drinks' },
  { name: 'vegetable juice', category: 'drinks' },
  { name: 'red wine', category: 'drinks' },
  { name: 'white wine', category: 'drinks' },
  { name: 'rosé wine', category: 'drinks' },
  { name: 'champagne', category: 'drinks' },
  { name: 'prosecco', category: 'drinks' },
  { name: 'beer', category: 'drinks' },
  { name: 'ale', category: 'drinks' },
  { name: 'lager', category: 'drinks' },
  { name: 'stout', category: 'drinks' },
  { name: 'vodka', category: 'drinks' },
  { name: 'whiskey', category: 'drinks' },
  { name: 'bourbon', category: 'drinks' },
  { name: 'scotch', category: 'drinks' },
  { name: 'rum', category: 'drinks' },
  { name: 'dark rum', category: 'drinks' },
  { name: 'light rum', category: 'drinks' },
  { name: 'gin', category: 'drinks' },
  { name: 'tequila', category: 'drinks' },
  { name: 'brandy', category: 'drinks' },
  { name: 'cognac', category: 'drinks' },

  // snacks
  { name: 'potato chips', category: 'snacks' },
  { name: 'tortilla chips', category: 'snacks' },
  { name: 'corn chips', category: 'snacks' },
  { name: 'pita chips', category: 'snacks' },
  { name: 'rice cakes', category: 'snacks' },
  { name: 'popcorn', category: 'snacks' },
  { name: 'pretzels', category: 'snacks' },
  { name: 'crackers', category: 'snacks' },
  { name: 'graham crackers', category: 'snacks' },
  { name: 'saltines', category: 'snacks' },
  { name: 'water crackers', category: 'snacks' },
  { name: 'granola', category: 'snacks' },
  { name: 'granola bars', category: 'snacks' },
  { name: 'trail mix', category: 'snacks' },
  { name: 'energy bar', category: 'snacks' },
  { name: 'protein bar', category: 'snacks' },
  { name: 'protein powder', category: 'snacks' },
  { name: 'seaweed snacks', category: 'snacks' },
  { name: 'pickles', category: 'snacks' },
  { name: 'dill pickles', category: 'snacks' },
  { name: 'sweet pickles', category: 'snacks' },
  { name: 'olives', category: 'snacks' },
  { name: 'green olives', category: 'snacks' },
  { name: 'black olives', category: 'snacks' },
  { name: 'kalamata olives', category: 'snacks' },
  { name: 'jerky', category: 'snacks' },
  { name: 'beef jerky', category: 'snacks' },
  { name: 'turkey jerky', category: 'snacks' },
  { name: 'hummus', category: 'snacks' },
  { name: 'guacamole', category: 'snacks' },
  { name: 'salsa', category: 'snacks' },
  { name: 'cheese sticks', category: 'snacks' },
  { name: 'yogurt cups', category: 'snacks' }
];

interface IngredientPickerProps {
  selectedIngredients: string[];
  onIngredientToggle: (ingredient: string) => void;
}

const IngredientPicker = ({ selectedIngredients, onIngredientToggle }: IngredientPickerProps) => {
  const [searchTerm, setSearchTerm] = useState('');
  const [expandedCategories, setExpandedCategories] = useState<string[]>([]);

  const filteredIngredients = ingredients.filter(ingredient =>
    ingredient.name.toLowerCase().includes(searchTerm.toLowerCase())
  );

  const categories = [...new Set(ingredients.map(i => i.category))];

  const toggleCategory = (category: string) => {
    setExpandedCategories(prev =>
      prev.includes(category)
        ? prev.filter(c => c !== category)
        : [...prev, category]
    );
  };

  const getIngredientsForCategory = (category: string) => {
    return filteredIngredients.filter(i => i.category === category);
  };

  return (
    <div className="w-full max-w-4xl mx-auto px-6">
      <div className="mb-8">
        <h2 className="text-2xl font-semibold mb-6 text-center">
          what do you have?
        </h2>
        
        <div className="relative mb-6">
          <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-muted-foreground w-4 h-4" />
          <Input
            type="text"
            placeholder="search ingredients..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="pl-10 bg-input border-border rounded-full h-12 text-base"
          />
        </div>

        {searchTerm ? (
          <div className="space-y-4">
            <div className="flex flex-wrap gap-2">
              {filteredIngredients.map((ingredient) => (
                <button
                  key={ingredient.name}
                  className={`ingredient-pill ${
                    selectedIngredients.includes(ingredient.name) ? 'selected' : ''
                  }`}
                  onClick={() => {
                    onIngredientToggle(ingredient.name);
                    setSearchTerm('');
                  }}
                >
                  {ingredient.name}
                </button>
              ))}
            </div>
          </div>
        ) : (
          <div className="space-y-6">
            {categories.map((category) => (
              <div key={category} className="space-y-3">
                <button
                  onClick={() => toggleCategory(category)}
                  className="flex items-center justify-between w-full text-left"
                >
                  <h3 className="text-lg font-medium">{category}</h3>
                  <span className="text-muted-foreground">
                    {expandedCategories.includes(category) ? '−' : '+'}
                  </span>
                </button>
                
                {expandedCategories.includes(category) && (
                  <div className="flex flex-wrap gap-2 pl-4">
                    {getIngredientsForCategory(category).map((ingredient) => (
                      <button
                        key={ingredient.name}
                        className={`ingredient-pill ${
                          selectedIngredients.includes(ingredient.name) ? 'selected' : ''
                        }`}
                        onClick={() => onIngredientToggle(ingredient.name)}
                      >
                        {ingredient.name}
                      </button>
                    ))}
                  </div>
                )}
              </div>
            ))}
          </div>
        )}

        {selectedIngredients.length > 0 && (
          <div className="mt-8 p-4 bg-card rounded-lg border">
            <h4 className="font-medium mb-3">selected ingredients ({selectedIngredients.length}):</h4>
            <div className="flex flex-wrap gap-2">
              {selectedIngredients.map((ingredient) => (
                <span
                  key={ingredient}
                  className="ingredient-selected"
                  onClick={() => onIngredientToggle(ingredient)}
                >
                  {ingredient} ×
                </span>
              ))}
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default IngredientPicker;