// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hpxwnvdclbudawzeswtc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhweHdudmRjbGJ1ZGF3emVzd3RjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyOTM0MDMsImV4cCI6MjA2OTg2OTQwM30.ypOkjIaSY1XIrF6uaZqp9cB2HF9ShZvsnnm2Lw3Y0HI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});